{{- if and .Values.receive.enabled (eq (include "thanos.receive.isSplit" .) "true") (or .Values.receive.router.serviceMonitor.enabled .Values.global.serviceMonitor.enabled) }}
{{- $sm := .Values.receive.router.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "thanos.receive.routerName" . }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
    {{- include "thanos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: receive-router
    {{- if .Values.global.serviceMonitor.labels }}{{ toYaml .Values.global.serviceMonitor.labels | nindent 4 }}{{- end }}
    {{- if $sm.labels }}{{ toYaml $sm.labels | nindent 4 }}{{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "router" "parent" "receive") | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "thanos.namespace" . }}
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" (dict "root" $ "component" "receive-router") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ default .Values.global.serviceMonitor.interval $sm.interval | quote }}
      scrapeTimeout: {{ default .Values.global.serviceMonitor.scrapeTimeout $sm.scrapeTimeout | quote }}
      {{- with (default .Values.global.serviceMonitor.scheme $sm.scheme) }}
      scheme: {{ . }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.tlsConfig $sm.tlsConfig) }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.basicAuth $sm.basicAuth) }}
      basicAuth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.metricRelabelings $sm.metricRelabelings) }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.relabelings $sm.relabelings) }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
