{{- if and .Values.receive.enabled (eq (include "thanos.receive.isSplit" .) "true") (or .Values.receive.router.serviceMonitor.enabled .Values.global.serviceMonitor.enabled) }}
{{- $sm := .Values.receive.router.serviceMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "thanos.receive.routerName" . }}
  labels:
    {{- if .Values.global.serviceMonitor.labels }}{{ toYaml .Values.global.serviceMonitor.labels | nindent 4 }}{{- end }}
    {{- if $sm.labels }}{{ toYaml $sm.labels | nindent 4 }}{{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "router" "parent" "receive") | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: receive-router
  endpoints:
    - port: http
      path: /metrics
      interval: {{ default .Values.global.serviceMonitor.interval $sm.interval | quote }}
      scrapeTimeout: {{ default .Values.global.serviceMonitor.scrapeTimeout $sm.scrapeTimeout | quote }}
      {{- with (default .Values.global.serviceMonitor.metricRelabelings $sm.metricRelabelings) }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.relabelings $sm.relabelings) }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
