{{- if and .Values.receive.enabled (eq (include "thanos.receive.isSplit" .) "true") .Values.global.networkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: receive-router
  name: {{ include "thanos.receive.routerName" . }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: http
        - port: remote-write
  podSelector:
    matchLabels:
      app.kubernetes.io/component: receive-router
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
    - Ingress
{{- end }}
