{{- if and .Values.receive.enabled (eq (include "thanos.receive.isSplit" .) "true") (or .Values.receive.router.pdb.enabled .Values.global.pdb.enabled) }}
{{- $minAvail := .Values.receive.router.pdb.minAvailable | default .Values.global.pdb.minAvailable -}}
{{- $maxUnavail := .Values.receive.router.pdb.maxUnavailable | default .Values.global.pdb.maxUnavailable -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thanos.receive.routerName" . }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: receive-router
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "router" "parent" "receive") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: receive-router
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if $minAvail }}
  minAvailable: {{ $minAvail }}
  {{- else if $maxUnavail }}
  maxUnavailable: {{ $maxUnavail }}
  {{- end }}
{{- end }}
