version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "helm"
    directories:
      - "/charts/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "helm"
