{{- if .Values.ruler.enabled }}
{{- $urls := .Values.ruler.query.urls }}
{{- if not $urls }}
{{- $urls = list (printf "http://%s:%v" (include "thanos.compName" (list . "query")) .Values.query.service.httpPort) }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.compName" (list . "ruler") }}-query
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "ruler-query") | nindent 4 }}
data:
  query-urls.yaml: |
    {{- range $url := $urls }}
    {{- $u := urlParse $url }}
    - static_configs:
        - {{ $u.host }}
      scheme: {{ $u.scheme }}
    {{- if and $u.path (ne $u.path "/") }}
      path_prefix: {{ $u.path }}
    {{- end }}
    {{- end }}
{{- end }}
