{{- if and .Values.ruler.enabled .Values.ruler.remoteWrite.enabled .Values.ruler.remoteWrite.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ruler.remoteWrite.secretName }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ruler
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "ruler") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ruler.remoteWrite.secretKey }}: |
    {{- tpl .Values.ruler.remoteWrite.config . | nindent 4 }}
{{- end -}}
