{{- if and .Values.global.serviceAccount.create .Values.global.rbac.create -}}
{{- if .Values.global.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
{{- /* One SA per enabled component */ -}}
{{- if and .Values.bucket.enabled .Values.bucket.bucketweb.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "bucketweb") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.compactor.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "compactor") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: compactor
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.query.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "query") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.queryFrontend.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "query-frontend") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-frontend
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.receive.enabled }}
{{- if eq (include "thanos.receive.isSplit" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "receive-ingester") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: receive-ingester
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "receive-router") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: receive-router
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "receive") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: receive
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .Values.ruler.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "ruler") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ruler
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.storegateway.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.compName" (list . "storegateway") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: storegateway
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}