{{- if and .Values.queryTls.enabled .Values.global.networkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: query-tls
    {{- include "thanos.labels" . | nindent 4 }}
  name: {{ include "thanos.compName" (list . "query-tls") }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: grpc
        - port: http
  podSelector:
    matchLabels:
      app.kubernetes.io/component: query-tls
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
    - Ingress
{{- end }}
