{{- if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.compName" (list . "query") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    {{- with .Values.query.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "query") | nindent 4 }}
    {{- with .Values.query.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.query.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: query
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "thanos.labels" . | nindent 8 }}
        app.kubernetes.io/component: query
      annotations:
        {{- toYaml .Values.global.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "thanos.serviceAccountName" . }}
      {{- include "thanos.affinity" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.imagePullSecrets" . | nindent 6 }}
      {{- include "thanos.podSC" (dict "root" . "key" "query") | nindent 6 }}
      containers:
        - name: query
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - query
            - --http-address=0.0.0.0:{{ .Values.query.service.httpPort }}
            - --grpc-address=0.0.0.0:{{ .Values.query.service.grpcPort }}
          {{- if .Values.queryTls.enabled }}
            - --endpoint=dnssrv+_grpc._tcp.{{ include "thanos.compName" (list . "query-tls") }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
          {{- end }}
          {{- if .Values.storegateway.enabled }}
            # - --endpoint={{ include "thanos.compName" (list . "storegateway") }}:{{ .Values.storegateway.service.grpcPort }}
            - --endpoint=dnssrv+_grpc._tcp.{{ include "thanos.compName" (list . "storegateway") }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
          {{- end }}
          {{- if .Values.receive.enabled }}
            # - --endpoint={{ include "thanos.compName" (list . "receive") }}-headless:{{ .Values.receive.service.grpcPort }}
            - --endpoint=dnssrv+_grpc._tcp.{{ include "thanos.compName" (list . "receive") }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
          {{- end }}
          {{- range .Values.query.replicaLabels }}
            - --query.replica-label={{ . }}
          {{- end }}
          {{- range .Values.query.stores }}
            - --endpoint={{ . }}
          {{- end }}
          {{- range .Values.query.extraArgs }}
            - {{ . | quote }}
          {{- end }}
          {{- include "thanos.extraEnvBlock" (dict "Values" .Values "component" "query") | nindent 10 }}
          {{- include "thanos.extraEnvFromBlock" (dict "Values" .Values "component" "query") | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.query.service.httpPort }}
            - name: grpc
              containerPort: {{ .Values.query.service.grpcPort }}
          {{- include "thanos.extraMountsBlock" (dict "root" . "key" "query") | nindent 10 }}
          {{- include "thanos.containerSC" (dict "root" . "key" "query") | nindent 10 }}
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
          {{- include "thanos.httpProbes" (dict "root" . "key" "query" "port" "http") | nindent 10 }}
        {{- include "thanos.extraContainers" (dict "Values" .Values "component" "query" "root" .) | nindent 8 }}
      {{- include "thanos.dnsConfig" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.initContainers" (dict "Values" .Values "component" "query" "root" .) | nindent 6 }}
      {{- include "thanos.nodeSelector" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.priorityClassName" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.tolerations" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.topologySpreadConstraints" (dict "Values" .Values "component" "query") | nindent 6 }}
      {{- include "thanos.extraVolumesBlock" (dict "root" . "key" "query") | nindent 6 }}
{{- end }}
