{{- if and .Values.storegateway.enabled (or .Values.storegateway.pdb.enabled .Values.global.pdb.enabled) }}
{{- $minAvail := .Values.storegateway.pdb.minAvailable | default .Values.global.pdb.minAvailable -}}
{{- $maxUnavail := .Values.storegateway.pdb.maxUnavailable | default .Values.global.pdb.maxUnavailable -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thanos.compName" (list . "storegateway") }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "storegateway") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: storegateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if $minAvail }}
  minAvailable: {{ $minAvail }}
  {{- else if $maxUnavail }}
  maxUnavailable: {{ $maxUnavail }}
  {{- end }}
{{- end }}
