{{- if and .Values.storegateway.enabled (or .Values.storegateway.pdb.enabled .Values.global.pdb.enabled) }}
{{- $minAvail := .Values.storegateway.pdb.minAvailable | default .Values.global.pdb.minAvailable -}}
{{- $maxUnavail := .Values.storegateway.pdb.maxUnavailable | default .Values.global.pdb.maxUnavailable -}}
{{- $shards := (include "thanos.storegateway.shards" . | fromYaml).shards }}
{{- range $i, $shard := $shards }}
{{- if $i }}
---
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $shard.name }}
  labels:
    {{- include "thanos.labels" $ | nindent 4 }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" $.Values "component" "storegateway") | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: storegateway
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- if $shard.isSharded }}
      thanos.io/storegateway-shard: {{ $shard.index | quote }}
      {{- end }}
  {{- if $minAvail }}
  minAvailable: {{ $minAvail }}
  {{- else if $maxUnavail }}
  maxUnavailable: {{ $maxUnavail }}
  {{- end }}
{{- end }}
{{- end }}
