{{- if and .Values.receive.enabled (eq (include "thanos.receive.mode" .) "standalone") }}
{{- $cfg := include "thanos.receive.cfg" . | fromYaml -}}
{{- if $cfg.httpRoute.enabled }}
{{ include "thanos.httpRoute" (list . "receive" $cfg.service.httpPort $cfg.httpRoute) }}
{{- end }}
{{- end }}
