{{- if and .Values.receive.enabled (eq (include "thanos.receive.mode" .) "standalone") }}
{{- $cfg := include "thanos.receive.cfg" . | fromYaml -}}
{{- $http := $cfg.ingress.http.enabled | ternary $cfg.ingress.http $cfg.ingress }}
{{- $ingresses := dict "http" $http "grpc" $cfg.ingress.grpc }}
{{- $sep := "" }}
{{- range $port, $ingress := $ingresses }}
{{- if $ingress.enabled }}
{{ $sep -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml $ingress.annotations | nindent 4 }}
    {{- include "thanos.annotations" (dict "Values" $.Values "component" "receive") | nindent 4 }}
  labels:
    {{- include "thanos.labels" $ | nindent 4 }}
  name: {{ include "thanos.compName" (list $ (printf "receive%s" (eq $port "http" | ternary "" (printf "-%s" $port)))) }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - backend:
              service:
                name: {{ include "thanos.compName" (list $ "receive") }}
                port:
                  name: {{ $port }}
            path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" }}
        {{- end }}
    {{- end }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- $sep = "---\n" }}
{{- end }}
{{- end }}
{{- end }}
