{{- if .Values.receive.enabled }}
{{- $cfg := include "thanos.receive.cfg" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.receive.workloadName" . }}
  labels:
    app.kubernetes.io/component: receive
    {{- include "thanos.labels" . | nindent 4 }}
    {{- with $cfg.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "receive") | nindent 4 }}
    {{- with $cfg.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $cfg.service.type }}
  ports:
    - name: http
      port: {{ $cfg.service.httpPort }}
      targetPort: http
    - name: remote-write
      port: {{ $cfg.service.remoteWritePort }}
      targetPort: remote-write
  selector:
    app.kubernetes.io/component: receive
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.receiveHeadless" . }}
  labels:
    app.kubernetes.io/component: receive
    {{- include "thanos.labels" . | nindent 4 }}
    {{- with $cfg.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "receive") | nindent 4 }}
    {{- with $cfg.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ $cfg.service.grpcPort }}
      targetPort: grpc
  selector:
    app.kubernetes.io/component: receive
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
