{{- if and .Values.bucket.enabled .Values.bucket.bucketweb.enabled .Values.global.networkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
  name: {{ include "thanos.compName" (list . "bucketweb") }}
  namespace: {{ include "thanos.namespace" . }}
spec:
  egress:
    - {}
  ingress:
    - ports:
        - port: http
  podSelector:
    matchLabels:
      {{- include "thanos.selectorLabels" (dict "root" $ "component" "bucketweb") | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
{{- end }}
