{{- if and .Values.bucket.enabled .Values.bucket.bucketweb.enabled (or .Values.bucket.bucketweb.pdb.enabled .Values.global.pdb.enabled) }}
{{- $minAvail := .Values.bucket.bucketweb.pdb.minAvailable | default .Values.global.pdb.minAvailable -}}
{{- $maxUnavail := .Values.bucket.bucketweb.pdb.maxUnavailable | default .Values.global.pdb.maxUnavailable -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thanos.compName" (list . "bucketweb") }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "bucketweb") | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" (dict "root" $ "component" "bucketweb") | nindent 6 }}
  {{- if $minAvail }}
  minAvailable: {{ $minAvail }}
  {{- else if $maxUnavail }}
  maxUnavailable: {{ $maxUnavail }}
  {{- end }}
{{- end }}
