{{- if and .Values.bucketReplicate.enabled .Values.bucketReplicate.objstoreTo.createSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bucketReplicate.objstoreTo.secretName }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucket-replicate
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "bucketReplicate") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bucketReplicate.objstoreTo.secretKey }}: |
    {{- tpl .Values.bucketReplicate.objstoreTo.config . | nindent 4 }}
{{- end -}}
