{{- if and .Values.queryFrontend.enabled (or .Values.queryFrontend.serviceMonitor.enabled .Values.global.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "thanos.compName" (list . "query-frontend") }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
    {{- include "thanos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: query-frontend
    {{- if .Values.global.serviceMonitor.labels }}{{ toYaml .Values.global.serviceMonitor.labels | nindent 4 }}{{- end }}
    {{- if .Values.queryFrontend.serviceMonitor.labels }}{{ toYaml .Values.queryFrontend.serviceMonitor.labels | nindent 4 }}{{- end }}
  annotations:
    {{- include "thanos.annotations" (dict "Values" .Values "component" "query-frontend") | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "thanos.namespace" . }}
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" (dict "root" $ "component" "query-frontend") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ default .Values.global.serviceMonitor.interval .Values.queryFrontend.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ default .Values.global.serviceMonitor.scrapeTimeout .Values.queryFrontend.serviceMonitor.scrapeTimeout | quote }}
      {{- with (default .Values.global.serviceMonitor.scheme .Values.queryFrontend.serviceMonitor.scheme) }}
      scheme: {{ . }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.tlsConfig .Values.queryFrontend.serviceMonitor.tlsConfig) }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.basicAuth .Values.queryFrontend.serviceMonitor.basicAuth) }}
      basicAuth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.metricRelabelings .Values.queryFrontend.serviceMonitor.metricRelabelings) }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.serviceMonitor.relabelings .Values.queryFrontend.serviceMonitor.relabelings) }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
